### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by thisisdumbstuff** [KeshHere/POE-Timeless-Jewel-Reverse-Search#1]
When you download Zip says there is a virus detected and wont open. What gives mate

**Comment by KeshHere** [comment]
I think this issue was related to some browser's web-defenders, which prevent downloading un-signed executable files (which is in the zip you are trying to download.)
Code signing certificates cost 300+ $ per year, which I can't cough up for a project that might not live more than 1 month I hope it's understandable.
Either try to use different browser to download (or some browser allows file to download when you click download anyways)
OR
Download the 5 CSVs and .au3 files separately from the Source code.zip and Install AutoIt3 to run the code (aka .au3 file).

I understand your concern about virus in .exe file from random person like me so I will encourage you to download the code and use the code itself. Although I assure you it is False positive detection.

**Comment by KeshHere** [comment]
If this is related to trying to open the exe file and it isn't running, try to put .exe in an exception in whichever antivirus you have if you trust me.
Otherwise it goes same as above, download the code (.au3), download the AutoIt3 and run the code.
Other solution is use poedb https://poedb.tw/us/TimelessJewel which has similar functions and it is on a website.
