### ISSUE TITLE
advanced search

### ISSUE THREAD

**Issue by Norby93** [KeshHere/POE-Timeless-Jewel-Reverse-Search#2]
is it possible to add a search by several parameters at the same time, as it is done in the PoE skill tree ("|" separator)

**Comment by KeshHere** [comment]
I think I replied to you on reddit already so I am gonna just copy paste that mag here just to keep track of this

"Aah i see, so you put stuff like "slum lord|superiority" in the search field and it will highlight them in the results, gotcha. I will implement this, as of now i am just waiting for GGG's response to this all, whether they will keep this as it is or change seeds and make it server sided? So once that is confirmed i will put more work in otherwise all this would be obsolete in coming weeks. Once it is confirmed i will add this feature in 24 hrs."

**Comment by KeshHere** [comment]
Added 'highlight' functionality for easy visibility. Cheers. 
"Timeless Jewel Reverse Search v1.5-beta"
