### ISSUE TITLE
why only 6 mods can be displayed at a time?

### ISSUE THREAD

**Issue by NomaratheF** [KeshHere/POE-Timeless-Jewel-Reverse-Search#3]
why only 6 mods can be displayed at a time?
(2) #% increased maximum Life
(1) #% increased Elemental Damage
(1) Minions deal #% increased Damage
(1) #% increased Critical Strike Chance
(1) #% increased Attack and Cast Speed
(1) Minions have #% increased Movement Speed
(3) #% increased Global Accuracy Rating
(1) +#% to Cold Resistance
(4) #% increased Flask Charges gained
(3) #% increased Damage with Poison
(4) #% increased Evasion Rating

for example seed 2365 brutal restirant has 11 different mods

**Comment by KeshHere** [comment]
I assume you have very high resolution desktop which is why it will bother you. But I made this keeping in mind average screen resolution of 1920x1080 at 125% scaling. It is possible to display even 11 at a time but showing mods that occur only once doesn't matter much in my opinion, which is why mods are shown in descending order of their occurence.  I have kept in mind that some mods are good even if they occur only once, because of that I have given them more weightage (such as +_intimidate,+_double_damage). If you feel like some mods are missing you can easily give them weight in code by adding them to $weightedmods on line 24.

**Comment by NomaratheF** [comment]
thanks a lot
